name: Demo Workflow

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Module
        uses: PSModule/Build-Module@main

      - name: Test Module
        uses: PSModule/Test-Module@main
        with:
          Verbose: true

      - name: Publish Module
        uses: PSModule/Publish-Module@main
        with:
          APIKey: ${{ secrets.APIKEY }}
